# -*- coding: utf-8 -*-
"""practice2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAIhwUqZSOUvtAiTfRRERoGGduepKkQ1
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# load test data
import pickle
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

root = "/content/drive/MyDrive/Colab Notebooks/ai-hardware"


with open(root + "/Practice1/imgs.pkl", "rb") as f:
    imgs = pickle.load(f)

mean = np.array([0.4913999, 0.48215866, 0.44653133])
std = np.array([0.24703476, 0.24348757, 0.26159027])

plt.figure(figsize=(15, 3), dpi=80)
base = np.zeros([32, 32*10, 3], dtype=np.uint8)
for i in range(10):
    data = imgs[i].transpose(0,1).transpose(1,2).numpy()
    data = (data * std + mean)*255
    data = data.astype(np.uint8)
    base[:, 32*i:32*(i+1), :] = data
plt.imshow(base)

classes = ('plane','car','bird','cat','deer','dog','frog','horse','ship','truck')

cd /content/drive/MyDrive/Colab Notebooks/ai-hardware/Practice1

# load model and pre-trained weight
import torch
from resnet import ResNet18, Pool

model = ResNet18(10)
model.load_state_dict(torch.load(root + "/Practice1/r18_c10.pth", weights_only=True))
model.eval()

# store (module, input_activation, output_activation) pairs
module_io = []

def forward_hook(module, input, output):
    module_io.append((module, input[0].detach().numpy(), output.detach().numpy()))

hooks = []
for name, module in model.named_modules():
    if isinstance(module, (torch.nn.Conv2d, torch.nn.BatchNorm2d, torch.nn.Linear, torch.nn.ReLU, Pool)):
        module.name = name
        hooks.append(module.register_forward_hook(forward_hook))

output = model(imgs)

for hook in hooks:
    hook.remove()

# check the output class
print(torch.argmax(output, dim=0))

# create your own custom kernel
import numpy as np
import time

# input : B x C_i x H_i x W_i
# weight: C_o x C_i x H_k x W_k
# stride: (H_s, W_s)
# padding: (H_p, W_p)
# output: B x C_o x H_o x W_o (Note: check https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html for H_o and W_o)
def custom_full_conv(input, weight, stride, padding):

    start = time.time()

    B, C_i, H_i, W_i = input.shape
    C_o, H_k, W_k = weight.shape[0], weight.shape[2], weight.shape[3]
    H_s, W_s = stride[0], stride[1]
    H_p, W_p = padding[0], padding[1]

    H_o = int(((H_i - H_k + 2*H_p)/H_s)+1)
    W_o = int(((W_i - W_k + 2*W_p)/W_s)+1)
    output = np.zeros((B, C_o, H_o, W_o), dtype=float)
    if H_p != 0 or W_p !=0:
        imagePadded = np.zeros((B, C_i, H_i + H_p*2, W_i + W_p*2), dtype=float)
        imagePadded[:, :, H_p:-H_p, W_p:-W_p] = input
    else:
        imagePadded = input

    for n in range (0, B):
        for t in range (0, C_o):
            for r in range (0, H_o):
                for c in range (0, W_o):
                    for d in range (0, C_i):
                        for i in range (0, H_k):
                            for j in range(0, W_k):
                                output[n][t][r][c] +=imagePadded[n][d][r*H_s+i][c*W_s+j]*weight[t][d][i][j]
    #  print ("output-conv", output.shape)
    end = time.time()
    exe_time = end-start

    return output, exe_time


# test the implementation
for (module, input, golden_output) in module_io:

    if (module.name == "conv1"):
        #  continue
        out, exe_time = custom_full_conv(input,
                               module.weight.data.numpy(),
                               module.stride,
                               module.padding)


        diff = np.linalg.norm(out - golden_output)

        if diff > 1e-3:
            print(f"module {module.name} has large error {diff}")
        else:
            print(f"module {module.name} has good implemetation", out[0,0,0,0], golden_output[0,0,0,0], exe_time)


    elif (module.name == "layer1.0.conv1"):
        #  continue
        out, exe_time = custom_full_conv(input,
                               module.weight.data.numpy(),
                               module.stride,
                               module.padding)


        diff = np.linalg.norm(out - golden_output)

        if diff > 1e-3:
            print(f"module {module.name} has large error {diff}")
        else:
            print(f"module {module.name} has good implemetation", out[0,0,0,0], golden_output[0,0,0,0], exe_time)

    else:
        pass

"""*Pactice* 2 (Convolution lowering + Matrix Tiling)"""

import numpy as np
import time

# input : B x C_i x H_i x W_i
# weight: C_o x C_i x H_k x W_k
# stride: (H_s, W_s)
# padding: (H_p, W_p)
# output: B x C_o x H_o x W_o (Note: check https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html for H_o and W_o)
def custom_full_conv(input, weight, stride, padding):

    start = time.time()
    B, C_i, H_i, W_i = input.shape
    C_o, H_k, W_k = weight.shape[0], weight.shape[2], weight.shape[3]
    H_s, W_s = stride[0], stride[1]
    H_p, W_p = padding[0], padding[1]

    H_o = int(((H_i - H_k + 2*H_p)/H_s)+1)
    W_o = int(((W_i - W_k + 2*W_p)/W_s)+1)
    output = np.empty((B, C_o, H_o, W_o), dtype=float)
    T = 64

    if H_p != 0 or W_p !=0:
        imagePadded = np.zeros((B, C_i, H_i + H_p*2, W_i + W_p*2), dtype=float)
        imagePadded[:, :, H_p:-H_p, W_p:-W_p] = input
    else:
        imagePadded = input

    for batch in range(0, B):
        # matrix multiplication (A_row X A_col) x (B_row x B_col) =>  size,  A_row X B_col
        A_row = int(H_o * W_o)
        A_col = int(C_i * H_k * W_k)
        W_row = int(C_i * H_k * W_k)
        W_col = int(C_o)


        input_tile = np.zeros((T, T), dtype=float)
        kernel_tile = np.zeros((T, T), dtype=float)
        partial_sum = np.zeros((A_row, W_col), dtype=float)

        # Convolution Lowring - kernel matrix 구현
        # Implemenet Your Code
        kernel_lowering = np.zeros((W_row, W_col), dtype=float)
        for c_o in range(0, C_o):
            for c_i in range(0, C_i):
                for h_k in range(0, H_k):
                    for w_k in range(0, W_k):
                        kernel_lowering[c_i * H_k * W_k + h_k * W_k + w_k, c_o] = weight[c_o, c_i, h_k, w_k]



        # Convolution Lowering - input image matrix
        # Loop over output spatial dimensions and flatten the receptive field
        input_lowering = np.zeros((A_row, A_col), dtype=float)
        for h_o in range(H_o):
            for w_o in range(W_o):
                row_idx = h_o * W_o + w_o
                col_idx = 0
                for c_i in range(C_i):
                    for h_k in range(H_k):
                        for w_k in range(W_k):
                            input_lowering[row_idx, col_idx] = imagePadded[batch, c_i, h_o * H_s + h_k, w_o * W_s + w_k]
                            col_idx += 1

        # tiling (Element-wise)
        for a_row in range(0, A_row, T):
            for w_col in range(0, W_col, T):
                # Determine the effective tile size
                tile_row_end = min(a_row + T, A_row)
                tile_col_end = min(w_col + T, W_col)

                # Iterate over the input_tile and kernel_tile
                for k in range(0, A_col, T):
                    # Define the current tile sizes
                    tile_a_col_end = min(k + T, A_col)

                    # Extract the current tiles
                    input_tile = input_lowering[a_row:tile_row_end, k:tile_a_col_end]
                    kernel_tile = kernel_lowering[k:tile_a_col_end, w_col:tile_col_end]

                    # Multiply tiles and accumulate in partial_sum
                    for i in range(tile_row_end - a_row):
                        for j in range(tile_col_end - w_col):
                            for l in range(tile_a_col_end - k):
                                partial_sum[a_row + i, w_col + j] += input_tile[i, l] * kernel_tile[l, j]


        output[batch] = partial_sum.reshape(H_o, W_o, C_o).transpose(2, 0, 1)




    end = time.time()
    exe_time = end-start
    #  print ("Excution time: ", exe_time)
    #  print ("output-conv", output.shape)
    return output, exe_time


# test the implementation
for (module, input, golden_output) in module_io:

    if (module.name == "conv1"):
        #  continue
        out, exe_time = custom_full_conv(input,
                               module.weight.data.numpy(),
                               module.stride,
                               module.padding)


        diff = np.linalg.norm(out - golden_output)

        if diff > 1e-3:
            print(f"module {module.name} has large error {diff}")
        else:
            print(f"module {module.name} has good implemetation", exe_time)


    elif (module.name == "layer1.0.conv1"):
        #  continue
        out, exe_time = custom_full_conv(input,
                               module.weight.data.numpy(),
                               module.stride,
                               module.padding)


        diff = np.linalg.norm(out - golden_output)

        if diff > 1e-3:
            print(f"module {module.name} has large error {diff}")
        else:
            print(f"module {module.name} has good implemetation", exe_time)

    else:
        continue

"""Pactice 2 (Convolution lowering + Matrix Tiling + Matrix Multiplication (np.matmul 사용))"""

# create your own custom kernel
import numpy as np
import time

# input : B x C_i x H_i x W_i
# weight: C_o x C_i x H_k x W_k
# stride: (H_s, W_s)
# padding: (H_p, W_p)
# output: B x C_o x H_o x W_o (Note: check https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html for H_o and W_o)
def custom_full_conv(input, weight, stride, padding):

    start = time.time()
    B, C_i, H_i, W_i = input.shape
    C_o, H_k, W_k = weight.shape[0], weight.shape[2], weight.shape[3]
    H_s, W_s = stride[0], stride[1]
    H_p, W_p = padding[0], padding[1]

    H_o = int(((H_i - H_k + 2*H_p)/H_s)+1)
    W_o = int(((W_i - W_k + 2*W_p)/W_s)+1)
    output = np.empty((B, C_o, H_o, W_o), dtype=float)

    if H_p != 0 or W_p !=0:
        imagePadded = np.zeros((B, C_i, H_i + H_p*2, W_i + W_p*2), dtype=float)
        imagePadded[:, :, H_p:H_p + H_i, W_p:W_p + W_i] = input
        # imagePadded[:, :, H_p:-H_p, W_p:-W_p] = input
    else:
        imagePadded = input

    # tile size T
    T = 64

    for b in range(0, B):
        # matrix multiplication (A_row X A_col) x (B_row x B_col) =>  size,  A_row X B_col
        A_row = int(H_o * W_o)
        A_col = int(C_i * H_k * W_k)
        W_row = int(C_i * H_k * W_k)
        W_col = int(C_o)

        input_lowering = np.zeros((A_row, A_col), dtype=float)
        input_tile = np.zeros((T, T), dtype=float)
        kernel_tile = np.zeros((T, T), dtype=float)
        partial_sum = np.zeros((A_row, W_col), dtype=float)

        # Convolution Lowring - kernel matrix
        # Implement Your Code
        kernel_lowering = np.zeros((W_row, W_col), dtype=float)
        for c_o in range(C_o):
            for c_i in range(C_i):
                for h_k in range(H_k):
                    for w_k in range(W_k):
                        kernel_lowering[c_i * H_k * W_k + h_k * W_k + w_k, c_o] = weight[c_o, c_i, h_k, w_k]



        # Convolution Lowering - input image matrix
        # Implement Your Code
        input_lowering = np.zeros((A_row, A_col), dtype=float)
        for h_o in range(H_o):
            for w_o in range(W_o):
                row_idx = h_o * W_o + w_o
                col_idx = 0
                for c_i in range(C_i):
                    for h_k in range(H_k):
                        for w_k in range(W_k):
                            input_lowering[row_idx, col_idx] = imagePadded[b, c_i, h_o * H_s + h_k, w_o * W_s + w_k]
                            col_idx += 1




        # tiling (using np.matmul)
        # Implement Your Code
        # tiling (Element-wise)

        for a_row in range(0, A_row, T):
            for w_col in range(0, W_col, T):
                # Determine the effective tile size
                tile_row_end = min(a_row + T, A_row)
                tile_col_end = min(w_col + T, W_col)

                for k in range(0, A_col, T):
                    # Define the current tile sizes
                    tile_a_col_end = min(k + T, A_col)

                    # Extract the current tiles
                    input_tile = input_lowering[a_row:tile_row_end, k:tile_a_col_end]
                    kernel_tile = kernel_lowering[k:tile_a_col_end, w_col:tile_col_end]

                    # Perform matrix multiplication for the current tile
                    partial_sum[a_row:tile_row_end, w_col:tile_col_end] += np.matmul(input_tile, kernel_tile)

        output[b] = partial_sum.reshape(H_o, W_o, C_o).transpose(2, 0, 1)


    end = time.time()
    exe_time = end-start
    # print ("Excution time: ", exe_time)
    # print ("output-conv", output.shape)
    # print ("input-conv", input.shape)
    # print ("padding, stride:", (H_s, W_s), (H_p, W_p), (H_o, W_o))
    return output, exe_time


# test the implementation
for (module, input, golden_output) in module_io:
    if isinstance(module, torch.nn.Conv2d):
        out, exe_time = custom_full_conv(input,
                               module.weight.data.numpy(),
                               module.stride,
                               module.padding)

    else:
        continue

    diff = np.linalg.norm(out - golden_output)

    if diff > 1e-3:
        print(f"module {module.name} has large error {diff}")
    else:
        print(f"module {module.name} has good implemetation", exe_time)

